Update ejecutar_script.yml

diff --git a/.github/workflows/ejecutar_script.yml b/.github/workflows/ejecutar_script.yml
--- a/.github/workflows/ejecutar_script.yml
+++ b/.github/workflows/ejecutar_script.yml
@@ -13,6 +13,25 @@ jobs:
       - name: Clonar repositorio
         uses: actions/checkout@v4
 
+      - name: Instalar WireGuard
+        run: sudo apt-get update && sudo apt-get install -y wireguard-tools
+
+      - name: Configurar WireGuard
+        run: |
+          sudo mkdir -p /etc/wireguard/
+          echo "${{ secrets.WG_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
+          sudo chmod 600 /etc/wireguard/wg0.conf
+
+      - name: Iniciar conexión WireGuard
+        run: sudo wg-quick up wg0
+
+      - name: Verificar conexión WireGuard
+        run: |
+          if ! curl --max-time 10 -s https://google.com > /dev/null; then
+            echo "::error:: Conexión no establecida; revisar credenciales"
+            exit 1
+          fi
+
       - name: Configurar Node.js
         uses: actions/setup-node@v4
 
